// Sport-specific performance metric catalog.
// Each metric is scored 0-10 by admin per user per sport.
// key = machine-safe id (used as MongoDB field name).

const m = (key, label) => ({ key, label });

export const SPORT_METRICS = {
  basketball: [
    m('dribbling_control', 'Dribbling Control'),
    m('crossover_moves', 'Crossover Moves'),
    m('layups_left', 'Layups (Left)'),
    m('layups_right', 'Layups (Right)'),
    m('blocks', 'Blocks'),
    m('free_throw_pct', 'Free Throw %'),
    m('defensive_stance', 'Defensive Stance'),
    m('help_defense', 'Help Defense'),
    m('on_ball_defense', 'On-ball Defense'),
    m('off_ball_movement', 'Off-ball Movement'),
    m('passing_accuracy', 'Passing Accuracy'),
    m('rebounding', 'Rebounding'),
    m('court_spacing', 'Court Spacing'),
    m('screen_setting', 'Screen Setting'),
    m('pick_and_roll', 'Pick & Roll Execution'),
    m('handling_under_pressure', 'Ball Handling Under Pressure'),
    m('shot_selection', 'Shot Selection'),
    m('transition_offense', 'Transition Offense'),
    m('transition_defense', 'Transition Defense'),
    m('three_point_accuracy', 'Three-point Shooting Accuracy'),
    m('mid_range_accuracy', 'Mid-range Shooting Accuracy'),
    m('shot_release_speed', 'Shot Release Speed'),
    m('catch_and_shoot_footwork', 'Footwork on Catch-and-Shoot'),
    m('weak_hand_dribbling', 'Weak-hand Dribbling Confidence'),
    m('passing_under_pressure', 'Passing Under Pressure'),
    m('post_up_moves', 'Post-up Moves'),
    m('rebound_positioning', 'Rebound Positioning & Box-out'),
    m('fast_break_decision', 'Fast Break Decision-making'),
    m('court_vision', 'Court Vision in Half-court Offense'),
    m('leadership', 'Leadership & Communication on Court'),
    m('strategy', 'Strategy'),
    m('mindset', 'Mindset'),
  ],

  skating: [
    m('balance', 'Balance'),
    m('balance_curves', 'Balance on Curves'),
    m('speed_test', 'Speed Test'),
    m('quick_stops', 'Quick Stops'),
    m('backward_skating', 'Backward Skating'),
    m('one_foot_glide', 'One-foot Glide'),
    m('turns', 'Turns'),
    m('spins', 'Spins'),
    m('small_jumps', 'Small Jumps'),
    m('obstacle_navigation', 'Obstacle Navigation'),
    m('slalom_drills', 'Slalom Drills'),
    m('braking_technique', 'Braking Technique'),
    m('endurance_laps', 'Endurance Laps'),
    m('flexibility', 'Flexibility'),
    m('reaction_time', 'Reaction Time'),
    m('foot_coordination', 'Foot Coordination'),
    m('skate_control', 'Skate Control'),
    m('hip_rotation', 'Hip Rotation'),
    m('cornering_speed', 'Cornering Speed'),
    m('confidence_ramps', 'Confidence on Ramps'),
    m('group_sync', 'Group Synchronization'),
    m('rhythm', 'Rhythm'),
    m('one_foot_balance_time', 'One-foot Balance Duration'),
    m('backward_crossovers', 'Backward Crossovers'),
    m('figure_eight', 'Figure-eight Pattern Execution'),
    m('transition_fwd_bwd', 'Transition Forward ↔ Backward'),
    m('turn_180_speed', '180° Turn Execution Speed'),
    m('spin_360_stability', '360° Spin Stability'),
    m('jump_landing_control', 'Jump Landing Control'),
    m('uphill_endurance', 'Uphill Skating Endurance'),
    m('downhill_control', 'Downhill Control & Braking Safety'),
    m('t_stop', 'T-stop Braking Efficiency'),
    m('hockey_stop', 'Hockey Stop Execution'),
    m('quick_direction_changes', 'Quick Direction Changes'),
    m('leg_strength', 'Leg Strength in Pushes'),
    m('high_speed_posture', 'Skating Posture in High-speed Turns'),
  ],

  karate: [
    m('kihon_basics', 'Kihon Basics'),
    m('stances', 'Stances'),
    m('punches', 'Punches'),
    m('kicks_front', 'Kicks (Front)'),
    m('kicks_roundhouse', 'Kicks (Roundhouse)'),
    m('kicks_side', 'Kicks (Side)'),
    m('kata_accuracy', 'Kata Accuracy'),
    m('kata_timing', 'Kata Timing'),
    m('sparring_points', 'Sparring Points'),
    m('counter_attacks', 'Counter-attacks'),
    m('posture', 'Posture'),
    m('discipline', 'Discipline'),
    m('focus', 'Focus'),
    m('confidence', 'Confidence'),
    m('respect', 'Respect'),
    m('bowing_etiquette', 'Bowing Etiquette'),
    m('kiai', 'Voice (Kiai)'),
    m('endurance', 'Endurance'),
    m('flexibility', 'Flexibility'),
    m('push_ups', 'Push-ups'),
    m('reaction_time', 'Reaction Time'),
    m('foot_coordination', 'Foot Coordination'),
    m('speed_drills', 'Speed Drills'),
    m('power_generation', 'Power Generation'),
    m('footwork_sparring', 'Footwork in Sparring'),
    m('front_kick_control', 'Front Kick Height & Control'),
    m('roundhouse_speed', 'Roundhouse Kick Height & Speed'),
    m('side_kick_balance', 'Side Kick Balance & Impact'),
    m('spinning_back_kick', 'Spinning Back Kick Accuracy'),
    m('jump_kick_control', 'Jump Kick Control'),
    m('punch_combo_speed', 'Punch Combination Speed'),
    m('reverse_punch_timing', 'Reverse Punch Timing'),
    m('hook_punch', 'Hook Punch Technique'),
    m('elbow_precision', 'Elbow Strike Precision'),
    m('shuto_execution', 'Knife-hand Strike (Shuto)'),
    m('block_reaction', 'Block Reaction Speed'),
    m('low_block_strength', 'Low Block Strength'),
    m('high_block_accuracy', 'High Block Accuracy'),
    m('kata_expression', 'Kata Expression (Emotional Energy)'),
    m('distance_control_kumite', 'Distance Control in Kumite'),
    m('feinting', 'Feinting Effectiveness in Sparring'),
    m('mental_focus_grading', 'Mental Focus During Grading/Exams'),
  ],
};

// Generic starter set for sports without a specific catalog yet.
export const GENERIC_METRICS = [
  m('technique', 'Technique'),
  m('speed', 'Speed'),
  m('endurance', 'Endurance'),
  m('strength', 'Strength'),
  m('agility', 'Agility'),
  m('focus', 'Focus'),
  m('discipline', 'Discipline'),
  m('teamwork', 'Teamwork'),
];

export function metricsForSport(sport_id) {
  return SPORT_METRICS[sport_id] || GENERIC_METRICS;
}

export function isValidMetricKey(sport_id, key) {
  return metricsForSport(sport_id).some(m => m.key === key);
}
